ShopTARgv23/Models/RealEstates/RealEstateCreateUpdateViewModel.cs
namespace ShopTARgv23.Models.RealEstates
{
    public class RealEstateCreateUpdateViewModel
    {
        public Guid? Id { get; set; }
        public string? Location { get; set; }
        public double? Size { get; set; }
        public int? RoomNumber { get; set; }
        public string? BuildingType { get; set; }

        public List<IFormFile> Files { get; set; }
        public List<RealEstateImageViewModel> Image { get; set; }
            = new List<RealEstateImageViewModel>();

        public DateTime? CreatedAt { get; set; }
        public DateTime? ModifiedAt { get; set; }
    }
}

ShopTARgv23/Models/RealEstates/RealEstateDeleteViewModel.cs
namespace ShopTARgv23.Models.RealEstates
{
    public class RealEstateDeleteViewModel
    {
        public Guid? Id { get; set; }
        public string? Location { get; set; }
        public double? Size { get; set; }
        public int? RoomNumber { get; set; }
        public string? BuildingType { get; set; }

        public DateTime? CreatedAt { get; set; }
        public DateTime? ModifiedAt { get; set; }

        public List<RealEstateImageViewModel> Image { get; set; }
            = new List<RealEstateImageViewModel>();
    }
}

ShopTARgv23/Models/RealEstates/RealEstateDetailsViewModel.cs
namespace ShopTARgv23.Models.RealEstates
{
    public class RealEstateDetailsViewModel
    {
        public Guid? Id { get; set; }
        public string? Location { get; set; }
        public double? Size { get; set; }
        public int? RoomNumber { get; set; }
        public string? BuildingType { get; set; }

        public DateTime? CreatedAt { get; set; }
        public DateTime? ModifiedAt { get; set; }

        public List<RealEstateImageViewModel> Image { get; set; }
            = new List<RealEstateImageViewModel>();
    }
}

ShopTARgv23/Models/RealEstates/RealEstateImageViewModel.cs
namespace ShopTARgv23.Models.RealEstates
{
    public class RealEstateImageViewModel
    {
        public Guid ImageId { get; set; }
        public string? ImageTitle { get; set; }
        public byte[]? ImageData { get; set; }
        public string? Image { get; set; }
        public Guid? RealEstateId { get; set; }
    }
}

ShopTARgv23/Models/RealEstates/RealEstateIndexViewModel.cs
namespace ShopTARgv23.Models.RealEstates
{
    public class RealEstateIndexViewModel
    {
        public Guid? Id { get; set; }
        public string? Location { get; set; }
        public double? Size { get; set; }
        public int? RoomNumber { get; set; }
        public string? BuildingType { get; set; }

        public DateTime? CreatedAt { get; set; }
        public DateTime? ModifiedAt { get; set; }
    }
}

ShopTARgv23/Models/RealEstates/RealEstatesCreateUpdateViewModel.cs
namespace ShopTARgv23.Models.RealEstates
{
    public class RealEstatesCreateUpdateViewModel
    {
        public Guid? Id { get; set; }
        public string? Location { get; set; }
        public double? Size { get; set; }
        public int? RoomNumber { get; set; }
        public string? BuildingType { get; set; }

        public List<IFormFile> Files { get; set; }
        public List<RealEstateImageViewModel> Image { get; set; }
            = new List<RealEstateImageViewModel>();

        public DateTime? CreatedAt { get; set; }
        public DateTime? ModifiedAt { get; set; }
    }
}

ShopTARgv23/Models/RealEstates/RealEstatesDeleteViewModel.cs
namespace ShopTARgv23.Models.RealEstates
{
    public class RealEstateDeleteViewModel
    {
        public Guid? Id { get; set; }
        public string? Location { get; set; }
        public double? Size { get; set; }
        public int? RoomNumber { get; set; }
        public string? BuildingType { get; set; }

        public DateTime? CreatedAt { get; set; }
        public DateTime? ModifiedAt { get; set; }

        public List<RealEstateImageViewModel> Image { get; set; }
            = new List<RealEstateImageViewModel>();
    }
}

ShopTARgv23/Models/RealEstates/RealEstatesDetailsViewModel.cs
namespace ShopTARgv23.Models.RealEstates
{
    public class RealEstateDetailsViewModel
    {
        public Guid? Id { get; set; }
        public string? Location { get; set; }
        public double? Size { get; set; }
        public int? RoomNumber { get; set; }
        public string? BuildingType { get; set; }

        public DateTime? CreatedAt { get; set; }
        public DateTime? ModifiedAt { get; set; }

        public List<RealEstateImageViewModel> Image { get; set; }
            = new List<RealEstateImageViewModel>();
    }
}

ShopTARgv23/Models/RealEstates/RealEstatesImageViewModel.cs
namespace ShopTARgv23.Models.RealEstates
{
    public class RealEstateImageViewModel
    {
        public Guid ImageId { get; set; }
        public string? ImageTitle { get; set; }
        public byte[]? ImageData { get; set; }
        public string? Image { get; set; }
        public Guid? RealEstateId { get; set; }
    }
}

ShopTARgv23/Models/RealEstates/RealEstatesIndexViewModel.cs
namespace ShopTARgv23.Models.RealEstates
{
    public class RealEstatesIndexViewModel
    {
        public Guid? Id { get; set; }
        public string? Location { get; set; }
        public double? Size { get; set; }
        public int? RoomNumber { get; set; }
        public string? BuildingType { get; set; }

        public DateTime? CreatedAt { get; set; }
        public DateTime? ModifiedAt { get; set; }
    }
}

ShopTARgv23/Controllers/RealEstatesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ShopTARgv23.ApplicationServices.Services;
using ShopTARgv23.Core.Dto;
using ShopTARgv23.Core.ServiceInterface;
using ShopTARgv23.Data;
using ShopTARgv23.Models.RealEstates;

namespace ShopTARgv23.Controllers
{
    public class RealEstatesController : Controller
    {
        private readonly ShopTARgv23Context _context;
        private readonly IRealEstateServices _realEstatesServices;
        private readonly IFileServices _fileServices;

        public RealEstatesController
            (
                ShopTARgv23Context context,
                IRealEstateServices realEstatesServices,
                IFileServices fileServices
            )
        {
            _context = context;
            _realEstatesServices = realEstatesServices;
            _fileServices = fileServices;
        }

        public IActionResult Index()
        {
            var result = _context.RealEstates
                .Select(x => new RealEstateIndexViewModel
                {
                    Id = x.Id,
                    Location = x.Location,
                    Size = x.Size,
                    RoomNumber = x.RoomNumber,
                    BuildingType = x.BuildingType,
                });

            return View(result);
        }

        [HttpGet]
        public IActionResult Create()
        {
            RealEstateCreateUpdateViewModel realEstates = new();

            return View("CreateUpdate", realEstates);
        }

        [HttpPost]
        public async Task<IActionResult> Create(RealEstateCreateUpdateViewModel vm)
        {
            var dto = new RealEstateDto()
            {
                Id = vm.Id,
                Size = vm.Size,
                Location = vm.Location,
                RoomNumber = vm.RoomNumber,
                BuildingType = vm.BuildingType,
                CreatedAt = vm.CreatedAt,
                ModifiedAt = vm.ModifiedAt,
                Files = vm.Files,
                Image = vm.Image
                    .Select(x => new FileToDatabaseDto
                    {
                        Id = x.ImageId,
                        ImageData = x.ImageData,
                        ImageTitle = x.ImageTitle,
                        RealEstateId = x.RealEstateId
                    }).ToArray()
            };

            var result = await _realEstatesServices.Create(dto);

            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index), vm);
        }

        [HttpGet]
        public async Task<IActionResult> Update(Guid id)
        {
            var realEstate = await _realEstatesServices.GetAsync(id);

            if (realEstate == null)
            {
                return NotFound();
            }

            var photos = await _context.FileToDatabases
                .Where(x => x.RealEstateId == id)
                .Select(y => new RealEstateImageViewModel
                {
                    RealEstateId = y.Id,
                    ImageId = y.Id,
                    ImageData = y.ImageData,
                    ImageTitle = y.ImageTitle,
                    Image = string.Format("data:image/gif;base64,{0}", Convert.ToBase64String(y.ImageData))
                }).ToArrayAsync();

            var vm = new RealEstateCreateUpdateViewModel();

            vm.Id = realEstate.Id;
            vm.Size = realEstate.Size;
            vm.Location = realEstate.Location;
            vm.RoomNumber = realEstate.RoomNumber;
            vm.BuildingType = realEstate.BuildingType;
            vm.CreatedAt = realEstate.CreatedAt;
            vm.ModifiedAt = realEstate.ModifiedAt;
            vm.Image.AddRange(photos);


            return View("CreateUpdate", vm);
        }

        [HttpPost]
        public async Task<IActionResult> Update(RealEstateCreateUpdateViewModel vm)
        {
            var dto = new RealEstateDto()
            {
                Id = vm.Id,
                Size = vm.Size,
                Location = vm.Location,
                RoomNumber = vm.RoomNumber,
                BuildingType = vm.BuildingType,
                CreatedAt = vm.CreatedAt,
                ModifiedAt = vm.ModifiedAt,
                Files = vm.Files,
                Image = vm.Image.Select(x => new FileToDatabaseDto
                {
                    Id = x.ImageId,
                    ImageData = x.ImageData,
                    ImageTitle = x.ImageTitle,
                    RealEstateId = x.RealEstateId,
                }).ToArray()
            };

            var result = await _realEstatesServices.Update(dto);

            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index), vm);
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var realEstate = await _realEstatesServices.GetAsync(id);

            if (realEstate == null)
            {
                return NotFound();
            }

            var photos = await _context.FileToDatabases
                .Where(x => x.RealEstateId == id)
                .Select(y => new RealEstateImageViewModel
                {
                    RealEstateId = y.Id,
                    ImageId = y.Id,
                    ImageData = y.ImageData,
                    ImageTitle = y.ImageTitle,
                    Image = string.Format("data:image/gif;base64,{0}", Convert.ToBase64String(y.ImageData))
                }).ToArrayAsync();

            var vm = new RealEstateDetailsViewModel();

            vm.Id = id;
            vm.Id = realEstate.Id;
            vm.Size = realEstate.Size;
            vm.Location = realEstate.Location;
            vm.RoomNumber = realEstate.RoomNumber;
            vm.BuildingType = realEstate.BuildingType;
            vm.CreatedAt = realEstate.CreatedAt;
            vm.ModifiedAt = realEstate.ModifiedAt;
            vm.Image.AddRange(photos);

            return View(vm);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            var realEstate = await _realEstatesServices.GetAsync(id);

            if (realEstate == null)
            {
                return NotFound();
            }

            var photos = await _context.FileToDatabases
                .Where(x => x.RealEstateId == id)
                .Select(y => new RealEstateImageViewModel
                {
                    RealEstateId = y.Id,
                    ImageId = y.Id,
                    ImageData = y.ImageData,
                    ImageTitle = y.ImageTitle,
                    Image = string.Format("data:image/gif;base64,{0}", Convert.ToBase64String(y.ImageData))
                }).ToArrayAsync();

            var vm = new RealEstateDeleteViewModel();

            vm.Id = id;
            vm.Id = realEstate.Id;
            vm.Size = realEstate.Size;
            vm.Location = realEstate.Location;
            vm.RoomNumber = realEstate.RoomNumber;
            vm.BuildingType = realEstate.BuildingType;
            vm.CreatedAt = realEstate.CreatedAt;
            vm.ModifiedAt = realEstate.ModifiedAt;
            vm.Image.AddRange(photos);

            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirmation(Guid id)
        {
            var realEstate = await _realEstatesServices.Delete(id);

            if (realEstate == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> RemoveImage(RealEstateImageViewModel file)
        {
            var dto = new FileToDatabaseDto()
            {
                Id = file.ImageId
            };

            var image = await _fileServices.RemoveImageFromDatabase(dto);

            if (image == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

ShopTARgv23/Views/RealEstates/CreateUpdate.cshtml
@model ShopTARgv23.Models.RealEstates.RealEstateCreateUpdateViewModel

@if (Model.Id.HasValue)
{
    <h1>Update</h1>
}
else
{
    <h1>Create</h1>
}


<div>
    <form method="post" enctype="multipart/form-data">
        <input asp-for="Id" type="hidden" />
        <input asp-for="CreatedAt" type="hidden" />

        <div class="form-group row">
            <label asp-for="Location" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Location" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Size" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Size" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="RoomNumber" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="RoomNumber" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="BuildingType" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="BuildingType" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Files" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-5">
                <div class="custom-file">
                    <input class="form-control" asp-for="Files" multiple type="file" />
                    <label class="custom-file-label">Choose file...</label>
                </div>
            </div>
        </div>

        <div>
            @foreach (var images in Model.Image)
            {
                <partial name="_Images" model="images" />
                <input asp-action="removeImage" asp-controller="realEstates" asp-route-imageId="@images.ImageId" type="submit" class="btn btn-danger" value="Remove Image" />
            }
        </div>

        <hr />

        @if (Model.Id.HasValue)
        {
            <input asp-action="update" asp-controller="realestates" type="submit" class="btn btn-primary" value="Update" />
        }
        else
        {
            <input asp-action="create" asp-controller="realestates" type="submit" class="btn btn-primary" value="Create" />
        }

        <a asp-action="index" class="btn btn-primary">Index</a>

    </form>
</div>

ShopTARgv23/Views/RealEstates/Delete.cshtml
@model ShopTARgv23.Models.RealEstates.RealEstateDeleteViewModel


<h1>Delete</h1>

<div>
    <h4>Spaceships</h4>
    <hr />
    <dl class="row">
        <div class="form-group row">
            <label asp-for="Id" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Id)
        </div>

        <div class="form-group row">
            <label asp-for="Location" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Location)
        </div>

        <div class="form-group row">
            <label asp-for="Size" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Size)
        </div>

        <div class="form-group row">
            <label asp-for="RoomNumber" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.RoomNumber)
        </div>

        <div class="form-group row">
            <label asp-for="BuildingType" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.BuildingType)
        </div>

        <div class="form-group row">
            <label asp-for="CreatedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.CreatedAt)
        </div>

        <div class="form-group row">
            <label asp-for="ModifiedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.ModifiedAt)
        </div>

        @foreach (var file in Model.Image)
        {
            <partial name="_Images" model="file" />
        }

        <form asp-action="DeleteConfirmation">
            <input type="hidden" asp-for="Id" />
            <input type="submit" value="Delete" class="btn btn-danger" />
            <a asp-action="Index" asp-controller="realEstates" class="btn btn-success">Back</a>
        </form>
    </dl>
</div>

ShopTARgv23/Views/RealEstates/Details.cshtml
@model ShopTARgv23.Models.RealEstates.RealEstateDetailsViewModel

<h1>Details</h1>

<div>
    <h4>Spaceships</h4>
    <hr />
    <dl class="row">
        <div class="form-group row">
            <label asp-for="Id" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Id)
        </div>

        <div class="form-group row">
            <label asp-for="Location" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Location)
        </div>

        <div class="form-group row">
            <label asp-for="Size" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Size)
        </div>

        <div class="form-group row">
            <label asp-for="RoomNumber" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.RoomNumber)
        </div>

        <div class="form-group row">
            <label asp-for="BuildingType" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.BuildingType)
        </div>

        <div class="form-group row">
            <label asp-for="CreatedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.CreatedAt)
        </div>

        <div class="form-group row">
            <label asp-for="ModifiedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.ModifiedAt)
        </div>

        @foreach (var images in Model.Image)
        {
            <partial name="_Images" model="images" />
        }

    </dl>
    <a asp-action="Index" asp-controller="realEstates" class="btn btn-danger">Back</a>
</div>

ShopTARgv23/Views/RealEstates/Index.cshtml
@using ShopTARgv23.Core.Domain
@model IEnumerable<ShopTARgv23.Models.RealEstates.RealEstateIndexViewModel>

@{
    int rowNumber = 1;
}

<div>
    <a asp-action="create" asp-controller="RealEstates" type="submit" class="btn btn-primary">Create</a>
</div>

<div class="h1">
    RealEstates
</div>

<form method="post">
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Nr</th>
                <th scope="col">Location</th>
                <th scope="col">Size</th>
                <th scope="col">RoomNumber</th>
                <th scope="col">BuildingType</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var realestates in Model)
            {
                <tr>
                    <td>@rowNumber</td>
                    <td>@realestates.Location</td>
                    <td>@realestates.Size</td>
                    <td>@realestates.RoomNumber</td>
                    <td>@realestates.BuildingType</td>
                    <td>
                        <a asp-action="details" asp-controller="realestates" asp-route-id="@realestates.Id" class="btn btn-info">Details</a>
                        <a asp-action="update" asp-controller="realestates" asp-route-id="@realestates.Id" class="btn btn-primary">Update</a>
                        <a asp-action="delete" asp-controller="realestates" asp-route-id="@realestates.Id" class="btn btn-outline-danger">Delete</a>
                    </td>
                </tr>

                rowNumber++;
            }
        </tbody>
    </table>
</form>

ShopTARgv23/Views/RealEstates/_Images.cshtml
@model ShopTARgv23.Models.RealEstates.RealEstateImageViewModel

<div class="form-group row col-sm-4 offset-2">
    <div>@Model.ImageTitle</div>
    <img class="card-img-top" src="@Model.Image" asp-append-version="true" />
</div>