ShopTARgv23/Models/Kindergarten/KindergartenCreateUpdateViewModel.cs
namespace ShopTARgv23.Models.Kindergarten
{
    public class KindergartenCreateUpdateViewModel
    {
        public Guid? Id { get; set; }
        public string? GroupName { get; set; }
        public int? ChildrenCount { get; set; }
        public string? KindergartenName { get; set; }
        public string? Teacher { get; set; }

        public List<IFormFile> Files { get; set; }
        public List<KindergartenImageViewModel> Image { get; set; }
            = new List<KindergartenImageViewModel>();
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
    }
}

ShopTARgv23/Models/Kindergarten/KindergartenDeleteViewModel.cs
namespace ShopTARgv23.Models.Kindergarten
{
    public class KindergartenDeleteViewModel
    {
        public Guid? Id { get; set; }
        public string? GroupName { get; set; }
        public int? ChildrenCount { get; set; }
        public string? KindergartenName { get; set; }
        public string? Teacher { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public List<KindergartenImageViewModel> Image { get; set; }
            = new List<KindergartenImageViewModel>();
    }
}

ShopTARgv23/Models/Kindergarten/KindergartenDetailsViewModel.cs
namespace ShopTARgv23.Models.Kindergarten
{
    public class KindergartenDetailsViewModel
    {
        public Guid? Id { get; set; }
        public string? GroupName { get; set; }
        public int? ChildrenCount { get; set; }
        public string? KindergartenName { get; set; }
        public string? Teacher { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public List<KindergartenImageViewModel> Image { get; set; }
            = new List<KindergartenImageViewModel>();
    }
}

ShopTARgv23/Models/Kindergarten/KindergartenImageViewModel.cs
namespace ShopTARgv23.Models.Kindergarten
{
    public class KindergartenImageViewModel
    {
        public Guid? ImageId { get; set; }
        public string? ImageTitle { get; set; }
        public byte[]? ImageData { get; set; }
        public string? Image { get; set; }
        public Guid? KindergartenId { get; set; }
    }
}

ShopTARgv23/Models/Kindergarten/KindergartenIndexViewModel.cs
namespace ShopTARgv23.Models.Kindergarten
{
    public class KindergartenIndexViewModel
    {
        public Guid? Id { get; set; }
        public string? GroupName { get; set; }
        public int? ChildrenCount { get; set; }
        public string? KindergartenName { get; set; }
        public string? Teacher { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
    }
}

ShopTARgv23/Models/Kindergartens/KindergartenDeleteViewModel.cs
namespace ShopTARgv23.Models.Kindergartens
{
    public class KindergartenDeleteViewModel
    {
        public Guid? Id { get; set; }
        public string? GroupName { get; set; }
        public int? ChildrenCount { get; set; }
        public string? KindergartenName { get; set; }
        public string? Teacher { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public List<KindergartenImageViewModel> Image { get; set; }
            = new List<KindergartenImageViewModel>();
    }
}

ShopTARgv23/Models/Kindergartens/KindergartenDetailsViewModel.cs
namespace ShopTARgv23.Models.Kindergartens
{
    public class KindergartenDetailsViewModel
    {
        public Guid? Id { get; set; }
        public string? GroupName { get; set; }
        public int? ChildrenCount { get; set; }
        public string? KindergartenName { get; set; }
        public string? Teacher { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public List<KindergartenImageViewModel> Image { get; set; }
            = new List<KindergartenImageViewModel>();
    }
}

ShopTARgv23/Models/Kindergartens/KindergartenImageViewModel.cs
namespace ShopTARgv23.Models.Kindergartens
{
    public class KindergartenImageViewModel
    {
        public Guid ImageId { get; set; }
        public string? ImageTitle { get; set; }
        public byte[]? ImageData { get; set; }
        public string? Image { get; set; }
        public Guid? KindergartenId { get; set; }
    }
}

ShopTARgv23/Models/Kindergartens/KindergartenIndexViewModel.cs
namespace ShopTARgv23.Models.Kindergartens
{
    public class KindergartenIndexViewModel
    {
        public Guid? Id { get; set; }
        public string? GroupName { get; set; }
        public int? ChildrenCount { get; set; }
        public string? KindergartenName { get; set; }
        public string? Teacher { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
    }
}

ShopTARgv23/Controllers/KindergartensController.cs
using Microsoft.AspNetCore.Mvc;
using ShopTARgv23.Core.Dto;
using ShopTARgv23.Core.ServiceInterface;
using ShopTARgv23.Data;
using Microsoft.EntityFrameworkCore;
using ShopTARgv23.ApplicationServices.Services;
using ShopTARgv23.Core.Domain;
using ShopTARgv23.Models.Kindergarten;

namespace ShopTARgv23.Controllers
{
    public class KindergartenController : Controller
    {
        private readonly ShopTARgv23Context _context;
        private readonly IKindergartenServices _kindergartenServices;
        private readonly IFileServices _fileServices;
        public KindergartenController
        (
            ShopTARgv23Context context,
            IKindergartenServices kindergartenServices,
            IFileServices fileServices)
        {
            _context = context;
            _kindergartenServices = kindergartenServices;
            _fileServices = fileServices;
        }

        public IActionResult Index()
        {
            var result = _context.Kindergarten
                .Select(x => new KindergartenIndexViewModel
                {
                    Id = x.Id,
                    GroupName = x.GroupName,
                    ChildrenCount = x.ChildrenCount,
                    KindergartenName = x.KindergartenName,
                    Teacher = x.Teacher,
                });

            return View(result);
        }

        [HttpGet]
        public IActionResult Create()
        {
            KindergartenCreateUpdateViewModel kindergarten = new();
            return View("CreateUpdate", kindergarten);
        }
        [HttpPost]
        public async Task<IActionResult> Create(KindergartenCreateUpdateViewModel vm)
        {
            var dto = new KindergartenDto()
            {
                Id = vm.Id,
                GroupName = vm.GroupName,
                ChildrenCount = vm.ChildrenCount,
                KindergartenName = vm.KindergartenName,
                Teacher = vm.Teacher,
                CreatedAt = vm.CreatedAt,
                UpdatedAt = vm.UpdatedAt,
                Files = vm.Files,
                Image = vm.Image
                    .Select(x => new FileToDatabaseDto
                    {
                        Id = x.ImageId,
                        ImageData = x.ImageData,
                        ImageTitle = x.ImageTitle,
                        KindergartenId = x.KindergartenId
                    }).ToArray()
            };
            var result = await _kindergartenServices.Create(dto);

            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index), vm);
        }

        [HttpGet]
        public async Task<IActionResult> Update(Guid id)
        {
            var kindergarten = await _kindergartenServices.Details(id);

            if (kindergarten == null) { return NotFound(); }

            var photos = await _context.FileToDatabases
                .Where(x => x.KindergartenId == id)
                .Select(y => new KindergartenImageViewModel
                {
                    KindergartenId = y.Id,
                    ImageId = y.Id,
                    ImageData = y.ImageData,
                    ImageTitle = y.ImageTitle,
                    Image = string.Format("data:image/gif;base64,{0}", Convert.ToBase64String(y.ImageData))
                }).ToArrayAsync();

            var vm = new KindergartenCreateUpdateViewModel();

            vm.Id = kindergarten.Id;
            vm.GroupName = kindergarten.GroupName;
            vm.ChildrenCount = kindergarten.ChildrenCount;
            vm.KindergartenName = kindergarten.KindergartenName;
            vm.Teacher = kindergarten.Teacher;
            vm.CreatedAt = kindergarten.CreatedAt;
            vm.UpdatedAt = kindergarten.UpdatedAt;
            vm.Image.AddRange(photos);

            return View("CreateUpdate", vm);
        }

        [HttpPost]
        public async Task<IActionResult> Update(KindergartenCreateUpdateViewModel vm)
        {
            var dto = new KindergartenDto()
            {
                Id = vm.Id,
                GroupName = vm.GroupName,
                ChildrenCount = vm.ChildrenCount,
                KindergartenName = vm.KindergartenName,
                Teacher = vm.Teacher,
                CreatedAt = vm.CreatedAt,
                UpdatedAt = vm.UpdatedAt,
                Files = vm.Files,
                Image = vm.Image.Select(x => new FileToDatabaseDto
                {
                    Id = x.ImageId,
                    ImageData = x.ImageData,
                    ImageTitle = x.ImageTitle,
                    KindergartenId = x.KindergartenId,
                }).ToArray()
            };

            var result = await _kindergartenServices.Update(dto);

            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var kindergarten = await _kindergartenServices.Details(id);

            if (kindergarten == null) { return NotFound(); }

            var photos = await _context.FileToDatabases
                .Where(x => x.KindergartenId == id)
                .Select(y => new KindergartenImageViewModel
                {
                    KindergartenId = y.Id,
                    ImageId = y.Id,
                    ImageData = y.ImageData,
                    ImageTitle = y.ImageTitle,
                    Image = string.Format("data:image/gif;base64,{0}", Convert.ToBase64String(y.ImageData))
                }).ToArrayAsync();


            var vm = new KindergartenDetailsViewModel();

            vm.Id = id;
            vm.Id = kindergarten.Id;
            vm.GroupName = kindergarten.GroupName;
            vm.ChildrenCount = kindergarten.ChildrenCount;
            vm.KindergartenName = kindergarten.KindergartenName;
            vm.Teacher = kindergarten.Teacher;
            vm.CreatedAt = kindergarten.CreatedAt;
            vm.UpdatedAt = kindergarten.UpdatedAt;
            vm.Image.AddRange(photos);

            return View(vm);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            var kindergarten = await _kindergartenServices.Details(id);
            if (kindergarten == null) { return NotFound(); }

            var photos = await _context.FileToDatabases
               .Where(x => x.KindergartenId == id)
               .Select(y => new KindergartenImageViewModel
               {
                   KindergartenId = y.Id,
                   ImageId = y.Id,
                   ImageData = y.ImageData,
                   ImageTitle = y.ImageTitle,
                   Image = string.Format("data:image/gif;base64,{0}", Convert.ToBase64String(y.ImageData))
               }).ToArrayAsync();

            var vm = new KindergartenDeleteViewModel();

            vm.Id = id;
            vm.Id = kindergarten.Id;
            vm.GroupName = kindergarten.GroupName;
            vm.ChildrenCount = kindergarten.ChildrenCount;
            vm.KindergartenName = kindergarten.KindergartenName;
            vm.Teacher = kindergarten.Teacher;
            vm.CreatedAt = kindergarten.CreatedAt;
            vm.UpdatedAt = kindergarten.UpdatedAt;
            vm.Image.AddRange(photos);

            return View(vm);
        }
        [HttpPost]
        public async Task<IActionResult> DeleteConfirmation(Guid id)
        {
            var kindergarten = await _kindergartenServices.Delete(id);

            if (kindergarten == null)
            {
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> RemoveImage(KindergartenImageViewModel file)
        {
            var dto = new FileToDatabaseDto()
            {
                Id = file.ImageId
            };

            var image = await _fileServices.RemoveImageFromDatabase(dto);

            if (image == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

ShopTARgv23/Views/Kindergarten/CreateUpdate.cshtml
@model ShopTARgv23.Models.Kindergarten.KindergartenCreateUpdateViewModel

@if (Model.Id.HasValue)
{
    <h1>Update</h1>
}
else
{
    <h1>Create</h1>
}

<div>
    <form method="post" enctype="multipart/form-data">
        <input asp-for="Id" type="hidden" />
        <input asp-for="CreatedAt" type="hidden" />
        <input asp-for="UpdatedAt" type="hidden" />

        <div class="form-group row">
            <label asp-for="GroupName" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="GroupName" class="form-control" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="ChildrenCount" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="ChildrenCount" class="form-control" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="KindergartenName" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="KindergartenName" class="form-control" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="Teacher" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Teacher" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Files" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-5">
                <div class="custom-file">
                    <input class="form-control" asp-for="Files" multiple type="file" />
                    <label class="custom-file-label">Choose file...</label>
                </div>
            </div>
        </div>

        <div>
            @foreach (var images in Model.Image)
            {
                <partial name="_Image" model="images" />
                <input asp-action="removeImage" asp-controller="kindergarten" asp-route-imageId="@images.ImageId" type="submit" class="btn btn-danger" value="Remove Image" />
            }
        </div>

        @if (Model.Id.HasValue)
        {
            <input asp-action="update" asp-controller="kindergarten" type="submit" class="btn btn-primary" value="Update"/>
        }
        else
        {
            <input asp-action="create" asp-controller="kindergarten" type="submit" class="btn btn-primary" value="Create" />
        }
        <a asp-action="index" class="btn btn-primary">Back</a>
    </form>
</div>

ShopTARgv23/Views/Kindergarten/Delete.cshtml
@model ShopTARgv23.Models.Kindergarten.KindergartenDeleteViewModel

<h1>Delete</h1>

<div>
    <h4>Kindergarten</h4>
    <hr />
    <dl class="row">
        <div class="form-group row">
            <label asp-for="Id" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Id)
        </div>
        <div class="form-group row">
            <label asp-for="GroupName" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.GroupName)
        </div>
        <div class="form-group row">
            <label asp-for="ChildrenCount" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.ChildrenCount)
        </div>
        <div class="form-group row">
            <label asp-for="KindergartenName" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.KindergartenName)
        </div>
        <div class="form-group row">
            <label asp-for="Teacher" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Teacher)
        </div>
        <div class="form-group row">
            <label asp-for="CreatedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.CreatedAt)
        </div>
        <div class="form-group row">
            <label asp-for="UpdatedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.UpdatedAt)
        </div>

        @foreach (var file in Model.Image)
        {
            <partial name="_Image" model="file" />
        }

        <form asp-action="DeleteConfirmation">
            <input type="hidden" asp-for="Id" />
            <input type="submit" value="Delete" class="btn btn-danger" />
            <a asp-action="Index" asp-asp-controller="kindergarten" class="btn btn-outline-danger">Back</a>
        </form>
    </dl>
</div>

ShopTARgv23/Views/Kindergarten/Details.cshtml
@model ShopTARgv23.Models.Kindergarten.KindergartenDetailsViewModel

<h1>Details</h1>

<div>
    <h4>Kindergarten</h4>
    <hr />
    <dl class="row">
        <div class="form-group row">
            <label asp-for="Id" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Id)
        </div>
        <div class="form-group row">
            <label asp-for="GroupName" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.GroupName)
        </div>
        <div class="form-group row">
            <label asp-for="ChildrenCount" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.ChildrenCount)
        </div>
        <div class="form-group row">
            <label asp-for="KindergartenName" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.KindergartenName)
        </div>
        <div class="form-group row">
            <label asp-for="Teacher" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Teacher)
        </div>
        <div class="form-group row">
            <label asp-for="CreatedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.CreatedAt)
        </div>
        <div class="form-group row">
            <label asp-for="UpdatedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.UpdatedAt)
        </div>

        @foreach (var images in Model.Image)
        {
            <partial name="_Image" model="images" />
        }

    </dl>
    <a asp-action="Index" asp-controller="kindergarten" class="btn btn-outline-primary">Back</a>
</div>

ShopTARgv23/Views/Kindergarten/Index.cshtml
@model IEnumerable<ShopTARgv23.Models.Kindergarten.KindergartenIndexViewModel>

@{
    int rowNumber = 1;
}

<div>
    <a asp-action="create" asp-controller="Kindergarten" type="submit" class="btn btn-primary">Create</a>
</div>

<div class="h1">
    Kindergarten
</div>

<form method="post">
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Nr</th>
                <th scope="col">GroupName</th>
                <th scope="col">ChildrenCount</th>
                <th scope="col">KindergartenName</th>
                <th scope="col">Teacher</th>
                <th scope ="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var kindergarten in Model)
            {
                <tr>
                    <td>@rowNumber</td>
                    <td>@kindergarten.GroupName</td>
                    <td>@kindergarten.ChildrenCount</td>
                    <td>@kindergarten.KindergartenName</td>
                    <td>@kindergarten.Teacher</td>
                    <td>
                        <a asp-action="details" asp-controller="kindergarten" asp-route-id="@kindergarten.Id" class="btn btn-outline-primary">Details</a>
                        <a asp-action="update" asp-controller="kindergarten" asp-route-id="@kindergarten.Id" class="btn btn-primary">Update</a>
                        <a asp-action="delete" asp-controller="kindergarten" asp-route-id="@kindergarten.Id" class="btn btn-outline-danger">Delete</a>
                    </td>
                </tr>
                rowNumber++;
            }
        </tbody>
    </table>
</form>

ShopTARgv23/Views/Kindergarten/_Image.cshtml
@model ShopTARgv23.Models.Kindergarten.KindergartenImageViewModel

<div class="form-group row col-sm-4 offset-2">
    <div>@Model.ImageTitle</div>
    <img class="card-img-top" src="@Model.Image" asp-append-version="true" />
</div>